### ISSUE TITLE
Python package still can be imported after `brew uninstall`

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [Homebrew/brew#13701]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/6aaf769281270e5eb5d134bdd34fcbef
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew uninstall mapserver

### What happened (include all command output)?

`brew install mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
2048
```

`brew uninstall mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mapscript' has no attribute 'MESSAGELENGTH'
```

### What did you expect to happen?

`brew install mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
2048
```

`brew uninstall mapserver`
`python3`
```
>>> import mapscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mapscript'
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Already described. Also, this happens not only to this package, but to any package installed with 
`system python, *Language::Python.setup_install_args(prefix, python)`
```

**Comment by SMillerDev** [comment]
@carlocab it's actually much simpeler. We don't install libraries for the system python. We install for the Homebrew python so this is expected behaviour.

**Comment by carlocab** [comment]
Oh, wait. Never mind. It does. Run
```
brew cleanup
```

**Comment by Oleksii-Svintsitskyi** [comment]
@SMillerDev python3 points to python@3.10 installed with `brew install python3`
```
company@Alekseis-MBP ~ % cd /usr/local/bin
company@Alekseis-MBP bin % ls -la | grep "python3"
-rwxrwxrwx    1 company  admin       248 Sep  3  2017 ipython3
lrwxr-xr-x    1 company  admin        42 Aug 15 15:01 python3 -> ../Cellar/python@3.10/3.10.6_1/bin/python3
lrwxr-xr-x    1 company  admin        49 Aug 15 15:01 python3-config -> ../Cellar/python@3.10/3.10.6_1/bin/python3-config
lrwxr-xr-x    1 company  admin        45 Aug 15 15:01 python3.10 -> ../Cellar/python@3.10/3.10.6_1/bin/python3.10
lrwxr-xr-x    1 company  admin        52 Aug 15 15:01 python3.10-config -> ../Cellar/python@3.10/3.10.6_1/bin/python3.10-config
lrwxr-xr-x    1 company  admin        43 Aug 15 13:20 python3.9 -> ../Cellar/python@3.9/3.9.13_3/bin/python3.9
lrwxr-xr-x    1 company  admin        50 Aug 15 13:20 python3.9-config -> ../Cellar/python@3.9/3.9.13_3/bin/python3.9-config
```

**Comment by Oleksii-Svintsitskyi** [comment]
> Oh, wait. Never mind. It does. Run
> 
> ```
> brew cleanup
> ```

Sorry, doesn't work for me :(
```
company@Alekseis-MBP ~ % brew install mapserver
==> Downloading https://ghcr.io/v2/homebrew/core/mapserver/manifests/7.6.4_8
Already downloaded: /Users/company/Library/Caches/Homebrew/downloads/aade11932c2d3f89d0acdb32687dc9346c8bab82f1628db21b3fb500cdd0598b--mapserver-7.6.4_8.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mapserver/blobs/sha256:375206c0885839f244be547433f983e683d11657c7ca0791
Already downloaded: /Users/company/Library/Caches/Homebrew/downloads/6c78892f1106cd1894781f2280668bb8d704c8da40c582470188106d4e48896e--mapserver--7.6.4_8.catalina.bottle.tar.gz
==> Pouring mapserver--7.6.4_8.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/mapserver/7.6.4_8: 130 files, 8.1MB
==> Running `brew cleanup mapserver`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
company@Alekseis-MBP ~ % brew uninstall mapserver
Uninstalling /usr/local/Cellar/mapserver/7.6.4_8... (130 files, 8.1MB)
company@Alekseis-MBP ~ % brew cleanup
company@Alekseis-MBP ~ % python3
Python 3.10.6 (main, Aug 11 2022, 13:47:18) [Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapscript
>>> dir(mapscript)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>>
```

**Comment by carlocab** [comment]
Hmmm, yea, that was mistaken. It _should_ be fixed by `brew cleanup` at least, though, even if not `brew uninstall`.

**Comment by Oleksii-Svintsitskyi** [comment]
@carlocab deleting subdirectory of `site-packages` definitely fixes the problem, but that is not very neat solution. This problem persists for many packages, like `tbb` or `lit`, but at the same time `six` and `libpython-tabulate` work fine with the similar installation method.

**Comment by carlocab** [comment]
> deleting subdirectory of `site-packages` definitely fixes the problem, but that is not very neat solution.

It may not be very neat, but there is no other solution:
```
❯ mkdir -p "$(brew --prefix)/lib/python3.10/site-packages/foo"
❯ python3 -c 'import foo'; echo $?
0
❯ rm -r "$(brew --prefix)/lib/python3.10/site-packages/foo"
❯ python3 -c 'import foo'; echo $?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
1
```

> This problem persists for many packages, like `tbb` or `lit`, but at the same time `six` and `libpython-tabulate` work fine with the similar installation method.

That's because `tbb` and `lit` leave behind essentially empty directory trees in `site-packages`, while `six` and `libpython-tabulate` do not.

**Comment by Oleksii-Svintsitskyi** [comment]
@carlocab thank you a lot! Where can I push initiative with `brew cleanup` automatically handling this?

**Comment by carlocab** [comment]
You can try to have a look at the code in [`cleanup.rb`](https://github.com/Homebrew/brew/blob/5047d4249e938d448ce8c80641beb4d42e90dbad/Library/Homebrew/cleanup.rb) yourself to try to fix this. Otherwise, we can wait and see if someone can find the time to have a look.

The right place is probably here:

https://github.com/Homebrew/brew/blob/5047d4249e938d448ce8c80641beb4d42e90dbad/Library/Homebrew/cleanup.rb#L492-L534

**Comment by Oleksii-Svintsitskyi** [comment]
@carlocab thanks!

**Comment by carlocab** [comment]
Let's keep this open, since it's not fixed yet.

**Comment by Oleksii-Svintsitskyi** [comment]
@carlocab okay, also this issue persists for pygobject3

**Comment by carlocab** [comment]
This will probably apply to any formula that installs a directory into `site-packages`. We don't need to enumerate those here.
