### ISSUE TITLE
Cannot install formulae from taps

### ISSUE THREAD

**Issue by miguelandres** [Homebrew/brew#14049]
### `brew config` output

```shell
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: (none)
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode-14.1-RC2.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: N/A
Xcode: 14.1 => /Applications/Xcode-14.1-RC2.app/Contents/Developer
Rosetta 2: false
```

### `brew doctor` output

```shell
brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing a formula from a tap that is not homebrew-core is failing, these are some public examples

```
brew tap spotify/homebrew-public
brew reinstall scio

brew tap miguelandres/homebrew-tap
brew reinstall dotfiles-rs
```

### What happened (include all command output)?

Both install commands get exactly the same output, complaining about mismatched versions of a superclass

```
 brew install scio
==> Downloading https://github.com/spotify/scio/releases/download/v0.11.6/scio-repl.jar
Already downloaded: /Users/miguely/Library/Caches/Homebrew/downloads/c7c5d57f27e6ec4a9ce13a0e358f339961fd42f5e2d5847a6d260b1a5b6344a3--scio-repl.jar
==> Installing scio from spotify/public
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:12: warning: already initialized constant Gem::VERSION
/Library/Ruby/Site/2.6.0/rubygems.rb:11: warning: previous definition of VERSION was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:14: warning: already initialized constant Gem::RubyGemsVersion
/Library/Ruby/Site/2.6.0/rubygems/compatibility.rb:17: warning: previous definition of RubyGemsVersion was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:18: warning: already initialized constant Gem::RbConfigPriorities
/Library/Ruby/Site/2.6.0/rubygems/compatibility.rb:20: warning: previous definition of RbConfigPriorities was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:27: warning: constant Gem::ConfigMap is deprecated
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/compatibility.rb:35: warning: constant Gem::ConfigMap is deprecated
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/defaults.rb:3: warning: already initialized constant Gem::DEFAULT_HOST
/Library/Ruby/Site/2.6.0/rubygems/defaults.rb:3: warning: previous definition of DEFAULT_HOST was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:117: warning: already initialized constant Gem::RUBYGEMS_DIR
/Library/Ruby/Site/2.6.0/rubygems.rb:115: warning: previous definition of RUBYGEMS_DIR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:122: warning: already initialized constant Gem::WIN_PATTERNS
/Library/Ruby/Site/2.6.0/rubygems.rb:129: warning: previous definition of WIN_PATTERNS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:131: warning: already initialized constant Gem::GEM_DEP_FILES
/Library/Ruby/Site/2.6.0/rubygems.rb:138: warning: previous definition of GEM_DEP_FILES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:141: warning: already initialized constant Gem::REPOSITORY_SUBDIRECTORIES
/Library/Ruby/Site/2.6.0/rubygems.rb:148: warning: previous definition of REPOSITORY_SUBDIRECTORIES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:153: warning: already initialized constant Gem::REPOSITORY_DEFAULT_GEM_SUBDIRECTORIES
/Library/Ruby/Site/2.6.0/rubygems.rb:161: warning: previous definition of REPOSITORY_DEFAULT_GEM_SUBDIRECTORIES was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:185: warning: already initialized constant Gem::LOADED_SPECS_MUTEX
/Library/Ruby/Site/2.6.0/rubygems.rb:171: warning: previous definition of LOADED_SPECS_MUTEX was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1345: warning: already initialized constant Gem::MARSHAL_SPEC_DIR
/Library/Ruby/Site/2.6.0/rubygems.rb:1294: warning: previous definition of MARSHAL_SPEC_DIR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:157: warning: already initialized constant Gem::Version::VERSION_PATTERN
/Library/Ruby/Site/2.6.0/rubygems/version.rb:158: warning: previous definition of VERSION_PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:158: warning: already initialized constant Gem::Version::ANCHORED_VERSION_PATTERN
/Library/Ruby/Site/2.6.0/rubygems/version.rb:159: warning: previous definition of ANCHORED_VERSION_PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:17: warning: already initialized constant Gem::Requirement::OPS
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:12: warning: previous definition of OPS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:27: warning: already initialized constant Gem::Requirement::SOURCE_SET_REQUIREMENT
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:22: warning: previous definition of SOURCE_SET_REQUIREMENT was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:30: warning: already initialized constant Gem::Requirement::PATTERN_RAW
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:25: warning: previous definition of PATTERN_RAW was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:35: warning: already initialized constant Gem::Requirement::PATTERN
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:30: warning: previous definition of PATTERN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:40: warning: already initialized constant Gem::Requirement::DefaultRequirement
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:35: warning: previous definition of DefaultRequirement was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/requirement.rb:314: warning: already initialized constant Gem::Version::Requirement
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:292: warning: previous definition of Requirement was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/platform.rb:198: warning: already initialized constant Gem::Platform::RUBY
/Library/Ruby/Site/2.6.0/rubygems/platform.rb:240: warning: previous definition of RUBY was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/platform.rb:204: warning: already initialized constant Gem::Platform::CURRENT
/Library/Ruby/Site/2.6.0/rubygems/platform.rb:246: warning: previous definition of CURRENT was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:9: warning: already initialized constant Gem::StubSpecification::PREFIX
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:9: warning: previous definition of PREFIX was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:12: warning: already initialized constant Gem::StubSpecification::OPEN_MODE
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:12: warning: previous definition of OPEN_MODE was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:18: warning: already initialized constant Gem::StubSpecification::StubLine::NO_EXTENSIONS
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:18: warning: previous definition of NO_EXTENSIONS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:21: warning: already initialized constant Gem::StubSpecification::StubLine::REQUIRE_PATHS
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:21: warning: previous definition of REQUIRE_PATHS was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/stub_specification.rb:31: warning: already initialized constant Gem::StubSpecification::StubLine::REQUIRE_PATH_LIST
/Library/Ruby/Site/2.6.0/rubygems/stub_specification.rb:31: warning: previous definition of REQUIRE_PATH_LIST was here
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification_policy.rb:4:in `<top (required)>': superclass mismatch for class SpecificationPolicy (TypeError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:16:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1365:in `<module:Gem>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:116:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/homebrew/Library/Homebrew/utils/gems.rb:47:in `setup_gem_environment!'
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:13:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `require_relative'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/build.rb:11:in `require_relative'
	from /opt/homebrew/Library/Homebrew/build.rb:11:in `<main>'
Error: Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20221026-29061-n4aerf.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /opt/homebrew/Library/Homebrew/build.rb /opt/homebrew/Library/Taps/spotify/homebrew-public/scio.rb` exited with 1.
```

### What did you expect to happen?

Successful installation? Particularly of formulae like dotfiles-rs which just extract a file.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap miguelandres/homebrew-tap
brew reinstall dotfiles-rs
```

This is probably the simplest.
```

**Comment by miguelandres** [comment]
FYI this was also happening before I upgraded to macOS 13

**Comment by carlocab** [comment]
Your install is broken.
```
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
```
What's the output of
```
git -C /opt/homebrew status
```
?

**Comment by miguelandres** [comment]
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by miguelandres** [comment]
Sorry I think I may have fixed it when running brew doctor during the steps above, and just made sure I had fixed everything before going over, re-ran brew config and got this

```
HOMEBREW_VERSION: 3.6.7-20-gc7f1a45
ORIGIN: https://github.com/Homebrew/brew
HEAD: c7f1a45eceea874dcc9e832f7acde24d8d7cf436
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d3241af77ab835123b40ef3da3c7627d0c7b0ce4
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode-14.1-RC2.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: N/A
Xcode: 14.1 => /Applications/Xcode-14.1-RC2.app/Contents/Developer
Rosetta 2: false
```

**Comment by miguelandres** [comment]
My guess is that it has to do with the homebrew ruby pointing to the system version instead of a more recent one,

```
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
```

since the actual exception I get at runtime is:

*/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification_policy.rb:4:in* `<top (required)>': *superclass mismatch for class SpecificationPolicy (TypeError)*

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification_policy.rb:4:in `<top (required)>': superclass mismatch for class SpecificationPolicy (TypeError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:16:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:1365:in `<module:Gem>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:116:in `<top (required)>'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /opt/homebrew/Library/Homebrew/utils/gems.rb:47:in `setup_gem_environment!'
	from /opt/homebrew/Library/Homebrew/standalone/load_path.rb:13:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `require_relative'
	from /opt/homebrew/Library/Homebrew/startup.rb:6:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `require_relative'
	from /opt/homebrew/Library/Homebrew/global.rb:4:in `<top (required)>'
	from /opt/homebrew/Library/Homebrew/build.rb:11:in `require_relative'
	from /opt/homebrew/Library/Homebrew/build.rb:11:in `<main>'
```

**Comment by carlocab** [comment]
Does doing
```
export HOMEBREW_FORCE_VENDOR_RUBY=1
```
help?

**Comment by MikeMcQuaid** [comment]
CC @Bo98 for Ruby weirdness in case it's related to recent changes.

**Comment by Bo98** [comment]
> ```
> /Library/Ruby/Site/2.6.0/rubygems
> ```

You've got a badly broken RubyGems installation.

In any case, this has been fixed #14041, which ignores any custom RubyGems installations. It appears to have fixed it for you as well when you updated.

**Comment by miguelandres** [comment]
This hasn't fixed my problem:

I still get the following error when running `brew install --verbose --debug dotfiles-rs`

```

Error: Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20221026-34093-11qoqx2.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /opt/homebrew/Library/Homebrew/build.rb /opt/homebrew/Library/Taps/miguelandres/homebrew-tap/Formula/dotfiles-rs.rb --verbose --debug` exited with 1.
/opt/homebrew/Library/Homebrew/sandbox.rb:157:in `exec'
/opt/homebrew/Library/Homebrew/formula_installer.rb:917:in `block in build'
/opt/homebrew/Library/Homebrew/utils/fork.rb:45:in `block (3 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
/opt/homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/opt/homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/opt/homebrew/Library/Homebrew/formula_installer.rb:905:in `build'
/opt/homebrew/Library/Homebrew/formula_installer.rb:450:in `install'
/opt/homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:339:in `each'
/opt/homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'

```

**Comment by miguelandres** [comment]
> ```shell
> export HOMEBREW_FORCE_VENDOR_RUBY=1
> ```

This did work, Carlo, thanks.

**Comment by Bo98** [comment]
> This hasn't fixed my problem:
> 
> I still get the following error when running `brew install --verbose --debug dotfiles-rs`
> 
> ```
> 
> Error: Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20221026-34093-11qoqx2.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /opt/homebrew/Library/Homebrew/build.rb /opt/homebrew/Library/Taps/miguelandres/homebrew-tap/Formula/dotfiles-rs.rb --verbose --debug` exited with 1.
> /opt/homebrew/Library/Homebrew/sandbox.rb:157:in `exec'
> /opt/homebrew/Library/Homebrew/formula_installer.rb:917:in `block in build'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:45:in `block (3 levels) in safe_fork'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
> /opt/homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
> /opt/homebrew/Library/Homebrew/formula_installer.rb:905:in `build'
> /opt/homebrew/Library/Homebrew/formula_installer.rb:450:in `install'
> /opt/homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
> /opt/homebrew/Library/Homebrew/install.rb:350:in `install_formula'
> /opt/homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
> /opt/homebrew/Library/Homebrew/install.rb:339:in `each'
> /opt/homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
> /opt/homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
> /opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
> ```

Looks like a sandbox issue. I would need more information like logs files to know, but it seems to be a completely different error.

**Comment by miguelandres** [comment]
Carlo's workaround works, though if you want some logs let me know.
