### ISSUE TITLE
FreeTDS Upgrade to version 0.95.95 fails due to broken download link

### ISSUE THREAD

**Issue by chapskev** [Homebrew/brew#158]
Ran 'brew upgrade' to upgrade all my packages after updating brew

Brew managed to upgrade all the packages except for freetds 

`==> Upgrading freetds
==> Downloading ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.80.tar.gz

curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/freetds-0.95.80.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "freetds"
Download failed: https://fossies.org/linux/privat/freetds-0.95.80.tar.gz
`

Tried to troubleshoot the issues and understand the problem and came up with the following finding
'brew upgrade freedts' is seaching for freedts from https://fossies.org/linux/privat/freetds-0.95.80.tar.gz
of which the link is not available as fossies only has the newest freetds release of [freetds-0.95.95](https://fossies.org/linux/privat/freetds-0.95.95.tar.gz/)

An update to the correct package would be highly appreciated. Thank you

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/facd5e26cbc3b32e21bd731142a5257b42c2d038. Thanks for the report!

**Comment by chapskev** [comment]
@DomT4 That was fast. 

Thank you

**Comment by chapskev** [comment]
@DomT4 there is still an issue with the upgrade. After the download, there is a mismatch of the checksum 

'==> Upgrading freetds
==> Downloading ftp://ftp.freetds.org/pub/freetds/stable/freetds-0.95.95.tar.bz2

curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/freetds-0.95.95.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 170bbe11ffe02cb38ec8f76605d13689e3e405862d7d083526667640f12ea95c
Actual: be7c90fc771f30411eff6ae3a0d2e55961f23a950a4d93c44d4c488006e64c70
Archive: /Library/Caches/Homebrew/freetds-0.95.95.tar.bz2
To retry an incomplete download, remove the file above.'

**Comment by DomT4** [comment]
Oops, that's because I'm an idiot who can't read filenames, one sec.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/commit/cf270a537743d32508fc8494141093677bb6fb8a

**Comment by sam-s** [comment]
same error this morning:
```
==> Upgrading 1 outdated package, with result:
freetds 1.00.16
==> Upgrading freetds
==> Using the sandbox
==> Downloading ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.16.tar.gz

curl: (56) response reading failed
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/freetds-1.00.16.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "freetds"
Download failed: https://fossies.org/linux/privat/freetds-1.00.16.tar.gz
```
