### ISSUE TITLE
Homebrew assumes receipts that may not exist: `undefined method `exist?' for nil:NilClass` when upgrading old formula

### ISSUE THREAD

**Issue by johnhawkinson** [Homebrew/brew#2436]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

### Bug reports:

This was previously analyzed in https://github.com/Homebrew/homebrew-core/issues/9391 and closed there because it was a `brew` issue, but no corresponding issue was created. It was suggested @alyssais was looking into it?

If an old formula was installed (in my case, with `brew diy` but that's probably not necessary given the analysis), and a new formula attempts to install over it, this appears:

```
pb3:~ jhawk$ brew install -i ntp
Unsetting PERL5LIB to protect you from yourself
Error: undefined method `exist?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/tab.rb:338:in `write'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:104:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
pb3:~ jhawk$ 
```

The workaround was to move aside /usr/local/Cellar/ntp:
```
pb3:~ jhawk$ cd /usr/local/Cellar/
pb3:Cellar jhawk$ ls -ld ntp*
drwxr-xr-x  3 jhawk  admin  102 Sep  7  2015 ntp
pb3:Cellar jhawk$ ls -l ntp
total 0
drwxr-xr-x  6 jhawk  admin  204 Sep  7  2015 4.2.8p3
pb3:Cellar jhawk$ mv ntp ntpstash
```

and then things work fine.

Although new users should not encounter this, homebrew should be robust for existing users and not generate inscrutable errors like this.

**Comment by ilovezfs** [comment]
You need to fill out the template otherwise we have no idea what version of brew or homebrew/core you're referring to.

**Comment by johnhawkinson** [comment]
> You need to fill out the template otherwise we have no idea what version of brew or homebrew/core you're referring to.

Sorry, I thought the existing analysis in https://github.com/Homebrew/homebrew-core/issues/9391 was sufficient. But for the sake of form:

```
pb3:~ jhawk$ brew config
Unsetting PERL5LIB to protect you from yourself
HOMEBREW_VERSION: 1.1.10-454-g72ca28fe56-dirty
ORIGIN: git@github.com:johnhawkinson/brew.git
HEAD: 72ca28fe56e3b48c0c9bb36462191147cc191a2f
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 11cc0189beebace39e92f57c8e9c7ee2b6f3978b
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
pb3:~ jhawk$ brew doctor
Unsetting PERL5LIB to protect you from yourself
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  lesstif
  ntp
  ntpstash
  numpy
  poppler
  python

Warning: Suspicious git origin remote found.

With a non-standard origin, Homebrew won't pull updates from
the main repository. The current git origin is:
  git@github.com:johnhawkinson/brew.git

Unless you have compelling reasons, consider setting the
origin remote to point at the main repository, located at:
  https://github.com/Homebrew/brew.git

Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library && git stash && git clean -d -f

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/opt/ntp
pb3:~ jhawk$ 
```

**Comment by ilovezfs** [comment]
```
HOMEBREW_VERSION: 1.1.10-454-g72ca28fe56-dirty
ORIGIN: git@github.com:johnhawkinson/brew.git
HEAD: 72ca28fe56e3b48c0c9bb36462191147cc191a2f
Last commit: 4 weeks ago
```
You're on your own fork, not on master or the stable tag, so even if this were fixed, you'd have no way of knowing.

**Comment by ilovezfs** [comment]
In any case, I think this is fixed now. Please file an issue in Homebrew/brew if it's still a problem after 1.1.12 ships, which should be tomorrow (and after you're actually on the 1.1.12 stable tag).

**Comment by johnhawkinson** [comment]
It still fails in 1.1.11-226-g974b5e2fa2, does that not have everything that would be in tomorrow's 1.1.12 tag?

```
pb3:~ jhawk$ brew install -i ntp
Unsetting PERL5LIB to protect you from yourself
Error: undefined method `exist?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/tab.rb:338:in `write'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:197:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
pb3:~ jhawk$ brew config
Unsetting PERL5LIB to protect you from yourself
HOMEBREW_VERSION: 1.1.11-226-g974b5e2fa2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 974b5e2fa26a162d29f97e996eb687b12a46a952
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ee00ee0a9696f4ad88686fd5a54534d0cfc241b
Core tap last commit: 43 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_74, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
pb3:~ jhawk$ 
```

It seems pointless to open a new issue...

**Comment by ilovezfs** [comment]
Thanks for checking.

CC @MikeMcQuaid @alyssais

**Comment by MikeMcQuaid** [comment]
> Sorry, I thought the existing analysis in Homebrew/homebrew-core#9391 was sufficient. But for the sake of form:

Just FYI: it's not just us being pedantic, this information is both helpful and necessary in figuring out the issue. For example, without @ilovezfs pointing our your `master` was different your first backtrace wasn't as useful as the line numbers didn't match up on the current `master`. Please fill it out every time, thanks.
