### ISSUE TITLE
Error: Failed to upgrade vendor Ruby — Error: Checksum mismatch

### ISSUE THREAD

**Issue by faxotherapy** [Homebrew/brew#4179]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
**I don't think others will be able to reproduce my errors.**
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
**My issue is irrelevant to this point, I think.**
- [x] ran `brew update` and can still reproduce the problem? **Yes**
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? **Yes**
```
brew doctor
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Already downloaded: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Can't locate strict.pm:   Permission denied at /usr/bin/shasum5.18 line 100.
BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 100.
Error: Checksum mismatch.
Expected: f1db8863543d256e6a8e704bf618025030b3d22a7a6b19749d19f599b5554212
Actual: 
Archive: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade vendor Ruby.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Already downloaded: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Can't locate strict.pm:   Permission denied at /usr/bin/shasum5.18 line 100.
BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 100.
Error: Checksum mismatch.
Expected: f1db8863543d256e6a8e704bf618025030b3d22a7a6b19749d19f599b5554212
Actual: 
Archive: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade vendor Ruby.
HOMEBREW_VERSION: 1.6.3-42-gd8ccdd9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d8ccdd9f26b6ee4923ec2d9b06c3c0ec2a2e3bd2
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 14302ab4c188338d6248d86947fa411f1023d427
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=~/Applications/
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:
- What you were trying to do (and why)
**I only did `brew update && brew upgrade` as I do regularly and suddenly `Error: Checksum mismatch` and `Error: Failed to upgrade vendor Ruby` appear. I never had those issues in the past.**
- What happened (include command output)
```
brew update
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Already downloaded: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
Can't locate strict.pm:   Permission denied at /usr/bin/shasum5.18 line 100.
BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 100.
Error: Checksum mismatch.
Expected: f1db8863543d256e6a8e704bf618025030b3d22a7a6b19749d19f599b5554212
Actual: 
Archive: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to upgrade vendor Ruby.
Updated 1 tap (caskroom/cask).
No changes to formulae.
```
- What you expected to happen
**I was simply expecting no error message as it's always the case during the upgrade process.**
- Step-by-step reproduction instructions (by running `brew` commands)
**All I did is the following:** `brew update && brew upgrade`

---
I run 10.11.6 OS X Capitan.

**Comment by scpeters** [comment]
~~~
Archive: /Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
~~~

Can you try removing that file?

**Comment by faxotherapy** [comment]
I cleaned the caches and removed that file. Then, Homebrew re-install it and put it in `~/Library/Caches/Homebrew`:
```
ls ~/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz 
/Users/Nathalie/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
```

**Comment by scpeters** [comment]
You need that file; it's just that the first version you downloaded may have been corrupted. After deleting, it should have downloaded a non-corrupt version. Is your error fixed now that a new version has been downloaded?

**Comment by faxotherapy** [comment]
thanks for your help. The tar file is well downloaded, but I still have the same error messages.

**Comment by MikeMcQuaid** [comment]
> Can't locate strict.pm:   Permission denied at /usr/bin/shasum5.18 line 100.
> BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 100.
> Error: Checksum mismatch.

This is the actual error here; you'll need to figure out why your `/usr/bin/shasum5.18` is broken. This is not an issue in Homebrew.

**Comment by microSoftware** [comment]
I have the same problem. Any command with brew (--version, doctor, update, install) return:

```
Can't locate strict.pm:   Permission denied at /usr/bin/shasum5.18 line 100.
BEGIN failed--compilation aborted at /usr/bin/shasum5.18 line 100.
Error: Checksum mismatch.
Expected: f1db8863543d256e6a8e704bf618025030b3d22a7a6b19749d19f599b5554212
Actual:
Archive: /Users/me/Library/Caches/Homebrew/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
```
I already remove and re-download portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz but same problem. It's strange because homebrew work perfectly fine until today.

I run on Mac 10.11.6

**Comment by MikeMcQuaid** [comment]
https://unix.stackexchange.com/questions/448661/perl-issue-on-os-x-el-capitan/448670#448670 may help here.
