### ISSUE TITLE
Libraries in /usr/local/lib are ignored during Brew builds if Xcode is installed.

### ISSUE THREAD

**Issue by indianajohn** [Homebrew/brew#502]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I just started from a brand new clean install of MacOSX El Capitan 10.11.5, and something in the way I set Brew/Xcode/Command Line Tools up made my Brew install unable to link anything against libraries in `/usr/local/lib`. Here were my steps.

0. Brand new install, nothing on the Mac.
1. Installed Brew.
2. Installed Xcode.
3. Ran `xcode-select --install`.

At this point I noticed that the PCL formula couldn't link against `-lGLUT` even though `libGLUT.dylib` was in `/usr/local/lib`. The same applied to VTK and hdf5. I also had problems with OpenNI2 and OpenNI, and I'm reasonably certain all of these things were due to the above problem.

I tried many things to troubleshoot the problem.
1. `rm -rf /usr/local/*; brew cleanup` and reinstalling brew.
2. `sudo rm -rf /Library/Developer/CommandLineTools; xcode-select --install`
3. `sudo xcode-select -s /Library/Developer/CommandLineTools`

The thing that finally fixed it was just removing Xcode entirely. While this is a working solution and I don't use Xcode a lot, I don't think it's a good one. There exists the possibility down the line that I will need to install Xcode again, and I would like to ensure that it won't remove my ability to link against libraries in `/usr/local/lib`.

I am avoiding installing Xcode again for now in the interest of actually getting work done, but if you needed me to for the purpose of troubleshooting again, I could.

I'm therefore opening this issue to a.) see if you guys have any fool-proof way to ensure that linking against libraries in `/usr/local/lib` is possible when both Xcode and Command Line Utilities are both installed and b.) document the issue. I was unable to uncover a case in which running `xcode-select --install`didn't resolve similar issues, and that would suggest that my sequence was unique (and i would like anybody who has this problem again to find this ticket), or this is related to recent updates released by Apple or Homebrew and you might see it down the line.

Thank you for your efforts.

**Comment by DomT4** [comment]
Are you sure your Homebrew is up-to-date? This smells very much like the problem fixed by https://github.com/Homebrew/brew/commit/bd4e24ae8f6db6ad6f0020352b0b8a15cb1c21e2. If it is up-to-date, can you provide a `brew config` & `brew doctor`? Thanks!

**Comment by indianajohn** [comment]
Homebrew was not up-to-date; that was probably the cause of my problems. I'll install Xcode tomorrow and report whether the problem persists.

**Comment by MikeMcQuaid** [comment]
Almost 100% sure this was due to https://github.com/Homebrew/brew/commit/bd4e24ae8f6db6ad6f0020352b0b8a15cb1c21e2 which is now fixed. Sorry for the pain!

**Comment by indianajohn** [comment]
Nope, thanks for the prompt fix.
