### ISSUE TITLE
Brew upgrade error on Mac Catalina 10.15

### ISSUE THREAD

**Issue by jtsom** [Homebrew/brew#6593]
Error displayed when doing a 'brew upgrade'

details in gist:

https://gist.github.com/jtsom/c1f127b16c765825d768b5eb4773c78e

**Comment by fxcoudert** [comment]
Transferred to `brew`, this seems to a affect a number of users

**Comment by xu-cheng** [comment]
I think this issue is caused by a cyclic dependency between ffmpeg and x264.

The ffmpeg formula depends on x264.

However, the bottle of x264 also depends on ffmpeg.
```
$ brew info --json x264 | jq '.[0].installed[0].runtime_dependencies'
[
  {
    "full_name": "ffmpeg",
    "version": "4.2.1"
  }
]
```

As such, the following function is called repeated in an infinite loop of recursion.

https://github.com/Homebrew/brew/blob/eac74ec6e6c4ae586cec8ebb2695ff3fe5d6b3bd/Library/Homebrew/cmd/upgrade.rb#L258-L301

You can reproduce the bug by the following command after installing ffmpeg and x264 formula in bottle.
```
brew unlink x264
mv $(brew --cellar)/x264/r2917_1 $(brew --cellar)/x264/r2917
brew link x264
brew upgrade
```

Further more, the current bottle of x264 is broken in addition to the aforementioned cyclic dependency issue:
```
$ brew linkage x264
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib (ffmpeg)
  /usr/local/opt/ffmpeg/lib/libavformat.58.dylib (ffmpeg)
  /usr/local/opt/ffmpeg/lib/libavresample.4.dylib (ffmpeg)
  /usr/local/opt/ffmpeg/lib/libavutil.56.dylib (ffmpeg)
  /usr/local/opt/ffmpeg/lib/libswresample.3.dylib (ffmpeg)
  /usr/local/opt/ffmpeg/lib/libswscale.5.dylib (ffmpeg)
Broken dependencies:
  /usr/local/opt/ffms2/lib/libffms2.4.dylib (ffms2)
Undeclared dependencies with linkage:
  ffmpeg
```

Some suggestions:

* Clearly, the x264 bottle should be rebuilt.
* You probably want to fix the logic of `broken_dependents` function in `upgrade.rb` to detect  cyclic dependencies.
* You probably want to investigate why brew-test-bot failing to reporting problems for the broken dependencies nor cyclic dependencies in the first place. I guess the root issue is that currently `brew linkage --test` did not report problem if there is any undeclared dependencies with linkage. You probably want to change it. I think brew-test-bot should fail when building the bottles if there are undeclared dependencies and they are not indirect dependencies (i.e. deps not in `brew deps <formula>`) .

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/brew/pull/6591

**Comment by CarterPape** [comment]
uuuhhhh I'm still getting this with 2.1.15. Maybe I need to report it to the package creator?

Here is the command and output:

```
$ brew upgrade
==> Upgrading 11 outdated packages:
libheif 1.5.1_1 -> 1.5.1_2
ffmpeg 4.2.1_1 -> 4.2.1_2
python 3.7.4_1 -> 3.7.5
shared-mime-info 1.14 -> 1.15
harfbuzz 2.6.2 -> 2.6.4
sqlite 3.29.0 -> 3.30.1
php 7.3.10 -> 7.3.11
youtube-dl 2019.10.22 -> 2019.10.29
x265 3.2 -> 3.2.1
sass/sass/sass 1.23.1 -> 1.23.3
imagemagick 7.0.8-68 -> 7.0.9-2
==> Upgrading sqlite 
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.30.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/38/38c39121f7634ec563bb201b483f66cf567dfe61e02624ffb06f620f11158ab1?__gd
######################################################################## 100.0%
==> Pouring sqlite-3.30.1.catalina.bottle.tar.gz
==> Caveats
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have sqlite first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/sqlite/3.30.1: 11 files, 3.9MB
Removing: /usr/local/Cellar/sqlite/3.29.0... (11 files, 3.9MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/sqlite--3.29.0.mojave.bottle.tar.gz... (1.9MB)
==> Upgrading ffmpeg 
==> Installing dependencies for ffmpeg: python, harfbuzz and x265
==> Installing ffmpeg dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.5.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/62/623d2a1110674974c0ea3ff0498c1ac865b858ba5293bdc29f3ce4dbd421fd42?__gd
######################################################################## 100.0%
==> Pouring python-3.7.5.catalina.bottle.tar.gz
==> /usr/local/Cellar/python/3.7.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/us
==> /usr/local/Cellar/python/3.7.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/us
==> /usr/local/Cellar/python/3.7.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/us
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.5: 3,972 files, 61.0MB
==> Installing ffmpeg dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-2.6.4.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fe/feed99de447de882a40417ee9b0739faf8827d01d3dfb25f01d89e73aa1f2444?__gd
######################################################################## 100.0%
==> Pouring harfbuzz-2.6.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/2.6.4: 158 files, 10.8MB
==> Installing ffmpeg dependency: x265
==> Downloading https://homebrew.bintray.com/bottles/x265-3.2.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/1b/1b0ba2cbc5a5776f28ca0e35e057dea92b3562f023e897c04eee202f8c6a5e41?__gd
######################################################################## 100.0%
==> Pouring x265-3.2.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/x265/3.2.1: 11 files, 35.2MB
==> Installing ffmpeg
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.2.1_2.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/11/11b16a8f9657e0826774d41133052b088f778a50f6f8037f641923cbb6b90335?__gd
######################################################################## 100.0%
==> Pouring ffmpeg-4.2.1_2.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.2.1_2: 287 files, 56.6MB
Removing: /usr/local/Cellar/ffmpeg/4.2.1_1... (287 files, 56.6MB)
Removing: /usr/local/Cellar/python/3.7.4_1... (3,924 files, 61.4MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/python--3.7.4_1.mojave.bottle.tar.gz... (14.6MB)
==> Upgrading shared-mime-info 
==> Downloading https://homebrew.bintray.com/bottles/shared-mime-info-1.15.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/13/137dfd734f5e7fe9b9ee80d1efa135f95a3ade95ceab83b2f79cd7ca1fd4d313?__gd
######################################################################## 100.0%
==> Pouring shared-mime-info-1.15.catalina.bottle.tar.gz
==> /usr/local/Cellar/shared-mime-info/1.15/bin/update-mime-database /usr/local/share/mime
🍺  /usr/local/Cellar/shared-mime-info/1.15: 85 files, 4.7MB
Removing: /usr/local/Cellar/shared-mime-info/1.14... (85 files, 4.7MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/shared-mime-info--1.14.catalina.bottle.tar.gz... (1.2MB)
Removing: /usr/local/Cellar/harfbuzz/2.6.2... (158 files, 10.7MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/harfbuzz--2.6.2.catalina.bottle.tar.gz... (2.5MB)
==> Upgrading php 
==> Downloading https://homebrew.bintray.com/bottles/php-7.3.11.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c0/c09396d2fc055d74f0f915c475ded38e8f7afac70ca5cc05546629e42fc654f1?__gd
######################################################################## 100.0%
==> Pouring php-7.3.11.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/pear
Target /usr/local/bin/pear
already exists. You may want to remove it:
  rm '/usr/local/bin/pear'

To force the link and overwrite all conflicting files:
  brew link --overwrite php

To list all files that would be deleted:
  brew link --overwrite --dry-run php

Possible conflicting files are:
/usr/local/bin/pear
/usr/local/bin/peardev
/usr/local/bin/pecl
/usr/local/lib/httpd/build/config.nice
/usr/local/lib/httpd/build/config_vars.mk
/usr/local/lib/httpd/build/instdso.sh
/usr/local/lib/httpd/build/library.mk
/usr/local/lib/httpd/build/ltlib.mk
/usr/local/lib/httpd/build/mkdir.sh
/usr/local/lib/httpd/build/program.mk
/usr/local/lib/httpd/build/rules.mk
/usr/local/lib/httpd/build/special.mk
/usr/local/lib/httpd/modules/httpd.exp
/usr/local/lib/httpd/modules/mod_access_compat.so
/usr/local/lib/httpd/modules/mod_actions.so
/usr/local/lib/httpd/modules/mod_alias.so
/usr/local/lib/httpd/modules/mod_allowmethods.so
/usr/local/lib/httpd/modules/mod_asis.so
/usr/local/lib/httpd/modules/mod_auth_basic.so
/usr/local/lib/httpd/modules/mod_auth_digest.so
/usr/local/lib/httpd/modules/mod_auth_form.so
/usr/local/lib/httpd/modules/mod_authn_anon.so
/usr/local/lib/httpd/modules/mod_authn_core.so
/usr/local/lib/httpd/modules/mod_authn_dbd.so
/usr/local/lib/httpd/modules/mod_authn_dbm.so
/usr/local/lib/httpd/modules/mod_authn_file.so
/usr/local/lib/httpd/modules/mod_authn_socache.so
/usr/local/lib/httpd/modules/mod_authnz_fcgi.so
/usr/local/lib/httpd/modules/mod_authz_core.so
/usr/local/lib/httpd/modules/mod_authz_dbd.so
/usr/local/lib/httpd/modules/mod_authz_dbm.so
/usr/local/lib/httpd/modules/mod_authz_groupfile.so
/usr/local/lib/httpd/modules/mod_authz_host.so
/usr/local/lib/httpd/modules/mod_authz_owner.so
/usr/local/lib/httpd/modules/mod_authz_user.so
/usr/local/lib/httpd/modules/mod_autoindex.so
/usr/local/lib/httpd/modules/mod_brotli.so
/usr/local/lib/httpd/modules/mod_buffer.so
/usr/local/lib/httpd/modules/mod_cache.so
/usr/local/lib/httpd/modules/mod_cache_disk.so
/usr/local/lib/httpd/modules/mod_cache_socache.so
/usr/local/lib/httpd/modules/mod_cgi.so
/usr/local/lib/httpd/modules/mod_cgid.so
/usr/local/lib/httpd/modules/mod_charset_lite.so
/usr/local/lib/httpd/modules/mod_data.so
/usr/local/lib/httpd/modules/mod_dav.so
/usr/local/lib/httpd/modules/mod_dav_fs.so
/usr/local/lib/httpd/modules/mod_dav_lock.so
/usr/local/lib/httpd/modules/mod_dbd.so
/usr/local/lib/httpd/modules/mod_deflate.so
/usr/local/lib/httpd/modules/mod_dialup.so
/usr/local/lib/httpd/modules/mod_dir.so
/usr/local/lib/httpd/modules/mod_dumpio.so
/usr/local/lib/httpd/modules/mod_echo.so
/usr/local/lib/httpd/modules/mod_env.so
/usr/local/lib/httpd/modules/mod_expires.so
/usr/local/lib/httpd/modules/mod_ext_filter.so
/usr/local/lib/httpd/modules/mod_file_cache.so
/usr/local/lib/httpd/modules/mod_filter.so
/usr/local/lib/httpd/modules/mod_headers.so
/usr/local/lib/httpd/modules/mod_heartbeat.so
/usr/local/lib/httpd/modules/mod_heartmonitor.so
/usr/local/lib/httpd/modules/mod_http2.so
/usr/local/lib/httpd/modules/mod_include.so
/usr/local/lib/httpd/modules/mod_info.so
/usr/local/lib/httpd/modules/mod_lbmethod_bybusyness.so
/usr/local/lib/httpd/modules/mod_lbmethod_byrequests.so
/usr/local/lib/httpd/modules/mod_lbmethod_bytraffic.so
/usr/local/lib/httpd/modules/mod_lbmethod_heartbeat.so
/usr/local/lib/httpd/modules/mod_log_config.so
/usr/local/lib/httpd/modules/mod_log_debug.so
/usr/local/lib/httpd/modules/mod_log_forensic.so
/usr/local/lib/httpd/modules/mod_logio.so
/usr/local/lib/httpd/modules/mod_macro.so
/usr/local/lib/httpd/modules/mod_md.so
/usr/local/lib/httpd/modules/mod_mime.so
/usr/local/lib/httpd/modules/mod_mime_magic.so
/usr/local/lib/httpd/modules/mod_mpm_event.so
/usr/local/lib/httpd/modules/mod_mpm_prefork.so
/usr/local/lib/httpd/modules/mod_mpm_worker.so
/usr/local/lib/httpd/modules/mod_negotiation.so
/usr/local/lib/httpd/modules/mod_proxy.so
/usr/local/lib/httpd/modules/mod_proxy_ajp.so
/usr/local/lib/httpd/modules/mod_proxy_balancer.so
/usr/local/lib/httpd/modules/mod_proxy_connect.so
/usr/local/lib/httpd/modules/mod_proxy_express.so
/usr/local/lib/httpd/modules/mod_proxy_fcgi.so
/usr/local/lib/httpd/modules/mod_proxy_fdpass.so
/usr/local/lib/httpd/modules/mod_proxy_ftp.so
/usr/local/lib/httpd/modules/mod_proxy_hcheck.so
/usr/local/lib/httpd/modules/mod_proxy_html.so
/usr/local/lib/httpd/modules/mod_proxy_http.so
/usr/local/lib/httpd/modules/mod_proxy_scgi.so
/usr/local/lib/httpd/modules/mod_proxy_uwsgi.so
/usr/local/lib/httpd/modules/mod_proxy_wstunnel.so
/usr/local/lib/httpd/modules/mod_ratelimit.so
/usr/local/lib/httpd/modules/mod_reflector.so
/usr/local/lib/httpd/modules/mod_remoteip.so
/usr/local/lib/httpd/modules/mod_reqtimeout.so
/usr/local/lib/httpd/modules/mod_request.so
/usr/local/lib/httpd/modules/mod_rewrite.so
/usr/local/lib/httpd/modules/mod_sed.so
/usr/local/lib/httpd/modules/mod_session.so
/usr/local/lib/httpd/modules/mod_session_cookie.so
/usr/local/lib/httpd/modules/mod_session_crypto.so
/usr/local/lib/httpd/modules/mod_session_dbd.so
/usr/local/lib/httpd/modules/mod_setenvif.so
/usr/local/lib/httpd/modules/mod_slotmem_plain.so
/usr/local/lib/httpd/modules/mod_slotmem_shm.so
/usr/local/lib/httpd/modules/mod_socache_dbm.so
/usr/local/lib/httpd/modules/mod_socache_memcache.so
/usr/local/lib/httpd/modules/mod_socache_redis.so
/usr/local/lib/httpd/modules/mod_socache_shmcb.so
/usr/local/lib/httpd/modules/mod_speling.so
/usr/local/lib/httpd/modules/mod_ssl.so
/usr/local/lib/httpd/modules/mod_status.so
/usr/local/lib/httpd/modules/mod_substitute.so
/usr/local/lib/httpd/modules/mod_suexec.so
/usr/local/lib/httpd/modules/mod_unique_id.so
/usr/local/lib/httpd/modules/mod_unixd.so
/usr/local/lib/httpd/modules/mod_userdir.so
/usr/local/lib/httpd/modules/mod_usertrack.so
/usr/local/lib/httpd/modules/mod_version.so
/usr/local/lib/httpd/modules/mod_vhost_alias.so
/usr/local/lib/httpd/modules/mod_watchdog.so
/usr/local/lib/httpd/modules/mod_xml2enc.so
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set php_ini /usr/local/etc/php/7.3/php.ini system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set php_dir /usr/local/share/pear system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set doc_dir /usr/local/share/pear/doc system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20180731 system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set bin_dir /usr/local/opt/php/bin system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set data_dir /usr/local/share/pear/data system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set man_dir /usr/local/share/man system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set test_dir /usr/local/share/pear/test system
==> /usr/local/Cellar/php/7.3.11/bin/pear config-set php_bin /usr/local/opt/php/bin/php system
==> /usr/local/Cellar/php/7.3.11/bin/pear update-channels
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.3/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Summary
🍺  /usr/local/Cellar/php/7.3.11: 521 files, 77.0MB
Removing: /usr/local/Cellar/php/7.3.10... (521 files, 77.0MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/php--7.3.10.catalina.bottle.tar.gz... (19.9MB)
==> Upgrading youtube-dl 
==> Downloading https://github.com/ytdl-org/youtube-dl/releases/download/2019.10.29/youtube-dl-2019.10.29.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/1039520/475b5000-fa13-11e9-9686-65a
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/youtube-dl/2019.10.29: 12 files, 2.1MB, built in 9 seconds
Removing: /usr/local/Cellar/youtube-dl/2019.10.22... (12 files, 2.1MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/youtube-dl--2019.10.22.tar.gz... (3MB)
Removing: /usr/local/Cellar/x265/3.2... (11 files, 35.2MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/x265--3.2.catalina.bottle.tar.gz... (4.8MB)
==> Upgrading sass/sass/sass 
==> Downloading https://github.com/sass/dart-sass/archive/1.23.3.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/1.23.3
######################################################################## 100.0%
==> /usr/local/opt/dart/bin/pub get
==> /usr/local/opt/dart/bin/dart2aot -Dversion=1.23.3 bin/sass.dart sass.dart.native
🍺  /usr/local/Cellar/sass/1.23.3: 9 files, 6.7MB, built in 39 seconds
Removing: /usr/local/Cellar/sass/1.23.1... (9 files, 6.7MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/sass--1.23.1.tar.gz... (329.4KB)
==> Upgrading libheif 
==> Downloading https://homebrew.bintray.com/bottles/libheif-1.5.1_2.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/2a/2a4e77094ff9668002f1344d51574538641384ab376e754c306d516bf95fdf81?__gd
######################################################################## 100.0%
==> Pouring libheif-1.5.1_2.catalina.bottle.tar.gz
==> /usr/local/opt/shared-mime-info/bin/update-mime-database /usr/local/share/mime
🍺  /usr/local/Cellar/libheif/1.5.1_2: 19 files, 2.3MB
Removing: /usr/local/Cellar/libheif/1.5.1_1... (19 files, 2.3MB)
==> Upgrading imagemagick 
==> Downloading https://homebrew.bintray.com/bottles/imagemagick-7.0.9-2.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a3/a34c7e283da440862a358a73f89469882ebf8768a799a355fd6a52e707458459?__gd
######################################################################## 100.0%
==> Pouring imagemagick-7.0.9-2.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/7.0.9-2: 1,479 files, 24.4MB
Removing: /usr/local/Cellar/imagemagick/7.0.8-68... (1,479 files, 24.4MB)
Removing: /Users/carterpape/Library/Caches/Homebrew/imagemagick--7.0.8-68.catalina.bottle.tar.gz... (9.5MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `initialize_dup'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `core_path'
/usr/local/Homebrew/Library/Homebrew/formula.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:37:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1518:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1775:in `declared_runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1553:in `runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1561:in `runtime_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:168:in `check_formula_deps'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:145:in `check_dylibs'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:27:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:280:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:280:in `block (3 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:274:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:274:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
```
then that block repeats a bunch…
```
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:367:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:114:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
$
```

Running `brew upgrade` again yielded no output; `brew cleanup` did nothing out of the ordinary, and I then ran `brew --version`, and it gave me:

```
$ brew --version 
Homebrew 2.1.15
Homebrew/homebrew-core (git revision 1ea06; last commit 2019-11-04)
Homebrew/homebrew-cask (git revision 932c87a; last commit 2019-11-04)
```

**Comment by CarterPape** [comment]
I see that this issue is now being tracked elsewhere: https://github.com/Homebrew/brew/issues/6671
