### ISSUE TITLE
Handle missing DevelopmentTools gracefully

### ISSUE THREAD

**Issue by Sidnicious** [Homebrew/brew#729]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug report:

This appeared in b33fe79478992da827317111370ab15d280e72c5. The following line throws when Xcode isn't installed, _or_ Xcode is <8 and the CLT aren't installed:

``` .rb
MacOS::Xcode.version >= "8.0" || MacOS::CLT.version >= "8.0"
```

Here's the output:

```
$ brew upgrade
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
radare2
==> Upgrading 2 outdated packages, with result:
go 1.7, node 6.4.0
Error: undefined method `>=' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/sidney/.homebrew/Library/Homebrew/extend/os/mac/extend/ENV/shared.rb:4:in `no_weak_imports?'
/Users/sidney/.homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:87:in `determine_cccfg'
/Users/sidney/.homebrew/Library/Homebrew/extend/ENV/super.rb:48:in `setup_build_environment'
/Users/sidney/.homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:93:in `setup_build_environment'
/Users/sidney/.homebrew/Library/Homebrew/extend/ENV.rb:23:in `with_build_environment'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:181:in `yielder'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:57:in `satisfied?'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:330:in `install_requirement_default_formula?'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:348:in `block in expand_requirements'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:216:in `block in prune?'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:214:in `catch'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:214:in `prune?'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:202:in `block (2 levels) in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/Users/sidney/.homebrew/Library/Homebrew/dependencies.rb:68:in `each'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:201:in `block in expand'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:200:in `each'
/Users/sidney/.homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/Users/sidney/.homebrew/Library/Homebrew/formula.rb:1272:in `recursive_requirements'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:341:in `expand_requirements'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:290:in `compute_dependencies'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/Users/sidney/.homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/Users/sidney/.homebrew/Library/Homebrew/cmd/upgrade.rb:88:in `upgrade_formula'
/Users/sidney/.homebrew/Library/Homebrew/cmd/upgrade.rb:67:in `block in upgrade'
/Users/sidney/.homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `each'
/Users/sidney/.homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `upgrade'
/Users/sidney/.homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

cc @MikeMcQuaid

**Comment by pftbest** [comment]
I have got this error:
```
$ brew update && brew upgrade
Already up-to-date.
==> Upgrading 8 outdated packages, with result:
imagemagick 6.9.5-7, libftdi 1.3, libpng 1.6.24
==> Upgrading imagemagick
==> Installing dependencies for imagemagick: libpng
==> Installing imagemagick dependency: libpng
==> Using the sandbox
Error: undefined method `>=' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/shared.rb:4:in `no_weak_imports?'
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:87:in `determine_cccfg'
/usr/local/Library/Homebrew/extend/ENV/super.rb:48:in `setup_build_environment'
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:93:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:86:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/commit/27fc2abacabd0990cce91eca42cc63ba05866e65.

**Comment by lazarillo** [comment]
Has this fix been pushed to the standard repo that I will hit when I perform `brew update`?  I am still seeing the error, and I have successfully updated (but cannot upgrade).

```
(python3) Mikes-Mac:~ mike$ brew update
Already up-to-date.
(python3) Mikes-Mac:~ mike$ brew upgrade
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb:16:in `<class:Octave>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:182:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:236:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:27:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
(python3) Mikes-Mac:~ mike$ 

```

I'd rather not have to pull directly from the GitHub repo, as I typically presume that packages that have been updated for the standard means of getting them are more robust.

**Comment by DomT4** [comment]
@lazarillo Can you provide your `brew config`? Thanks!

**Comment by lazarillo** [comment]
Yes, here it is:

```
Mikes-Mac:~ mike$ brew config
HOMEBREW_VERSION: 1.0.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a5565d8fd600bc2883ed76ca8708d08588d1ef3f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f04cd55678864dfcbed56696fe43e7a461931f9
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: N/A
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.7.0_75, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: N/A
X11: 2.7.8 => /opt/X11
Mikes-Mac:~ mike$ 
```

**Comment by lazarillo** [comment]
And I also often run it in an anaconda environment that uses Python3 as its default, as well, which is the config when it failed in my initial comment.  Here is that brew config:

```
(python3) Mikes-Mac:~ mike$ brew config
HOMEBREW_VERSION: 1.0.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a5565d8fd600bc2883ed76ca8708d08588d1ef3f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f04cd55678864dfcbed56696fe43e7a461931f9
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: N/A
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/mike/anaconda/envs/python3/bin/python => /Users/mike/anaconda/envs/python3/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.7.0_75, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: N/A
X11: 2.7.8 => /opt/X11
(python3) Mikes-Mac:~ mike$ 
```

**Comment by vladshablinsky** [comment]
Happens because there is no `clang` installed. And I'm not sure what should be changed in this case: formula or something else. 

`homebrew-science/octave.rb` never checks if `DevelopmentTools.installed?`is true. `DevelopmentTools.clang_version` simply returns `nil` because there is no `clang`. 

```ruby
# octave.rb
# ...
  if OS.mac? && DevelopmentTools.clang_version < "7.0"
# ...
```

**Comment by lazarillo** [comment]
Thanks for that information!  That's right!  I was having some issues with Apple's App Store no longer recognizing my Apple ID, so I had to uninstall XCode, thereby losing clang, and I forgot to re-install it.  In the process now, but it's a long process.  I will follow up to see if I still have the problem.

**Comment by DomT4** [comment]
We make assumptions in core as well about `DevelopmentTools.xyz` actually returning something that isn't `nil`.

Maybe we should be handling that more carefully in the `DevelopmentTools` code in this repo so it doesn't panic in slightly confusing ways, but I'm not sure how supported trying to use Homebrew with no developer tools at all installed is at this point? @MikeMcQuaid

**Comment by DomT4** [comment]
@lazarillo If you prefer to, you can use just the Command Line Tools with Homebrew. We don't mandate a full Xcode installation, except for building certain formulae from source where upstream expects or demands Xcode for whatever reason.

**Comment by lazarillo** [comment]
That was the problem!  Things worked OK once I re-installed XCode / clang.  My bad.

**Comment by MikeMcQuaid** [comment]
> Maybe we should be handling that more carefully in the DevelopmentTools code in this repo so it doesn't panic in slightly confusing ways, but I'm not sure how supported trying to use Homebrew with no developer tools at all installed is at this point? @MikeMcQuaid

@DomT4 We should handle this case more gracefully, agreed.

**Comment by MikeMcQuaid** [comment]
CC @woodruffw In case you were interested in picking some of this up given your penultimate GSoC. Feels like something we could write tests for, too.

**Comment by woodruffw** [comment]
@MikeMcQuaid Sure thing!

In principle, IIRC, `DevelopmentTools` and its ilk shouldn't be used (unguarded) in places that bottling logic needs to hit, since we no longer need to assume the presence of `install_name_tool` or `otool`.

I'm going to completely clean my Hombrew/Xcode setup and see what (if anything) breaks with a variety of bottle installs and *how* it fails with a variety of source installs.

**Comment by MikeMcQuaid** [comment]
@woodruffw Sounds amazing, thanks!

**Comment by woodruffw** [comment]
At a cursory glance, it looks like we've regressed pretty far in terms of CLT-less bottle installs.

`brew install git` on a fresh CLT-less Homebrew installation *should* have complained a bit and then proceeded, but failed with a long procession of these:

```
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git must be installed and in your PATH!
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
```

I'm going to continue looking into this.

**Comment by woodruffw** [comment]
The remaining errors we're seeing (`You must: brew install git`) are being caused by early use of `git` in `brew.sh`:

```bash
if [[ -z "$HOMEBREW_DEVELOPER" ]]
then
  export HOMEBREW_GIT_CONFIG_FILE="$HOMEBREW_REPOSITORY/.git/config"
  HOMEBREW_GIT_CONFIG_DEVELOPERMODE="$(git config --file="$HOMEBREW_GIT_CONFIG_FILE" --get homebrew.devcmdrun)"
  if [[ "$HOMEBREW_GIT_CONFIG_DEVELOPERMODE" = "true" ]]
  then
    export HOMEBREW_DEV_CMD_RUN="1"
  fi
fi

if [[ -f "$HOMEBREW_LIBRARY/Homebrew/cmd/$HOMEBREW_COMMAND.sh" ]]
then
  HOMEBREW_BASH_COMMAND="$HOMEBREW_LIBRARY/Homebrew/cmd/$HOMEBREW_COMMAND.sh"
elif [[ -f "$HOMEBREW_LIBRARY/Homebrew/dev-cmd/$HOMEBREW_COMMAND.sh" ]]
then
  if [[ -z "$HOMEBREW_DEVELOPER" ]]
  then
    git config --file="$HOMEBREW_GIT_CONFIG_FILE" --replace-all homebrew.devcmdrun true
    export HOMEBREW_DEV_CMD_RUN="1"
  fi
  HOMEBREW_BASH_COMMAND="$HOMEBREW_LIBRARY/Homebrew/dev-cmd/$HOMEBREW_COMMAND.sh"
fi
```
and in `utils/analytics.sh` for the same purpose (getting config values from `git config`). These errors only occur on the first time `brew` is run after installation with `--force-curl`, as `git` is installed from a bottle via `Utils.ensure_git_installed!`.

Since these are ingrained fairly deeply in Homebrew, there's no really clean way to avoid them. Here are some ideas I had, in no particular order:

* Guard the calls in `brew.sh` and `analytics.sh` with checks for git's installation. These checks would have to be extremely conservative, as we can't guarantee that `/usr/local/bin` isn't the CLT stub and we don't want CLT-less users to have to click-out of popups when they've already made it clear that they don't want to install the CLT.

* Simply remove the `echo` from the `git` shims. This'll stop the 7-8 error messages that occur when `brew` is run for the first time after a `--force-curl` install, as `git` is automatically installed after that. This is the simplest "fix", although those annoying developer tools will still pop up since the shims are still being invoked.

* Replace `git --config` with a utility-agnostic configuration system, like a YAML or JSON file. This would get rid of the errors by virtue of eliminating the need for `git` before an opportunity for installation arises, but requires us to migrate away from the current configuration system.

* Vendor `git` with Homebrew, the same way `ruby` has been vendored. By making this mandatory, we could skip all the pain associated with checking for `git` and just ensure its installation early-on.

**Comment by woodruffw** [comment]
Just for replication, this is what I've done to `brew.sh`:

```diff
diff --git a/Library/Homebrew/brew.sh b/Library/Homebrew/brew.sh
index cbf39d0..0fd689d 100644
--- a/Library/Homebrew/brew.sh
+++ b/Library/Homebrew/brew.sh
@@ -1,4 +1,4 @@
-HOMEBREW_VERSION="$(git -C "$HOMEBREW_REPOSITORY" describe --tags --dirty 2>/dev/null)"
+#HOMEBREW_VERSION="$(git -C "$HOMEBREW_REPOSITORY" describe --tags --dirty 2>/dev/null)"
 HOMEBREW_USER_AGENT_VERSION="$HOMEBREW_VERSION"
 if [[ -z "$HOMEBREW_VERSION" ]]
 then
@@ -217,7 +217,7 @@ esac
 if [[ -z "$HOMEBREW_DEVELOPER" ]]
 then
   export HOMEBREW_GIT_CONFIG_FILE="$HOMEBREW_REPOSITORY/.git/config"
-  HOMEBREW_GIT_CONFIG_DEVELOPERMODE="$(git config --file="$HOMEBREW_GIT_CONFIG_FILE" --get homebrew.devcmdrun)"
+  # HOMEBREW_GIT_CONFIG_DEVELOPERMODE="$(git config --file="$HOMEBREW_GIT_CONFIG_FILE" --get homebrew.devcmdrun)"
   if [[ "$HOMEBREW_GIT_CONFIG_DEVELOPERMODE" = "true" ]]
   then
     export HOMEBREW_DEV_CMD_RUN="1"
@@ -231,7 +231,7 @@ elif [[ -f "$HOMEBREW_LIBRARY/Homebrew/dev-cmd/$HOMEBREW_COMMAND.sh" ]]
 then
   if [[ -z "$HOMEBREW_DEVELOPER" ]]
   then
-    git config --file="$HOMEBREW_GIT_CONFIG_FILE" --replace-all homebrew.devcmdrun true
+    # git config --file="$HOMEBREW_GIT_CONFIG_FILE" --replace-all homebrew.devcmdrun true
     export HOMEBREW_DEV_CMD_RUN="1"
   fi
   HOMEBREW_BASH_COMMAND="$HOMEBREW_LIBRARY/Homebrew/dev-cmd/$HOMEBREW_COMMAND.sh"
```

And I've exported `HOMEBREW_NO_ANALYTICS=1` to guard-out the `git` invocations in `utils/analytics.sh`. This gets rid of all the shim errors.

A CLT `git` popup still appears during bottle installations, which means something somewhere is still trying to invoke `/usr/bin/git`. I'll try to trace that down as well.

**Comment by MikeMcQuaid** [comment]
@woodruffw Given the `echo` is on `stderr` I think `2>/dev/null` on each of these early Git invocations would make sense. I think `brew update` and `brew analytics` are the only cases where we should demand Git and fail hard otherwise. I do agree with you that longer-term it may just be a better idea to remove this `echo` from the Git shim, return a failing exit code anyway and move the logic to `brew update` and `brew analytics`.

**Comment by MikeMcQuaid** [comment]
> as we can't guarantee that /usr/local/bin isn't the CLT stub

We kinda can guarantee that. It's a safe assumption that `/usr/bin/git` is the only case that may be a stub.

**Comment by woodruffw** [comment]
> It's a safe assumption that /usr/bin/git is the only case that may be a stub.

Whoops, that's what I meant :smile:

**Comment by woodruffw** [comment]
Testing on my system, #1380 makes CLT-less Homebrew installations essentially identical to Homebrew with CLT. One CLT prompt still pops up the first time `brew install` is invoked, probably because the `git` shims are still trying to execute the `/usr/bin/git` stub at least once. That needs to be fixed eventually, but canceling the prompt for the time being allows `brew` to function normally in the expected use case (i.e., installing bottles).

**Comment by MikeMcQuaid** [comment]
@woodruffw Great, nice work! Agreed about 💀ing that stub call but otherwise: 🆒!

**Comment by MikeMcQuaid** [comment]
Going to consider this closed out for now given @woodruffw's great work here. Feel free to dump comments in here if there's other related things folks feel should be addressed here.
