### ISSUE TITLE
Deprecated commands used in completions, 

### ISSUE THREAD

**Issue by Amorymeltzer** [Homebrew/brew#8709]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use bash tab completion to show outdated casks.

## What happened (include command output)
<details>
  <summary>Command output</summary>

`> brew cask outdated <TAB>`

`> brew cask outdated Warning: Calling brew cask list is deprecated! Use brew list --cask instead.`

</details>

Some `cask` sub commands have been incorporated into `brew` and are deprecated (see e.g. #8390 for a helpful list), but they persist in a few places, in particular in the docs (#8629, see also [Homebrew/homebrew-cask#88682](https://github.com/Homebrew/homebrew-cask/pull/88682)).  The completion scripts also use some of these deprecated commands.  Beyond fixing notable offenders from cask (like `list` and `outdated`), brew sub commands (like `list` and `outdated`) also need to learn about the `--cask` flag.

- [x] [bash](https://github.com/Homebrew/brew/blob/f9dd8ae6f908089d5d99441d0ae7cedc76059372/completions/bash/brew) (#8710)
- [ ] [fish](https://github.com/Homebrew/brew/blob/f9dd8ae6f908089d5d99441d0ae7cedc76059372/completions/fish/brew.fish)
- [x] [zsh](https://github.com/Homebrew/brew/blob/f9dd8ae6f908089d5d99441d0ae7cedc76059372/completions/zsh/_brew_cask) (Some done in #8650, more in #8837)

I suppose there could be a discussion about whether to remove deprecated commands while deprecated but present/functioning.

**Comment by MikeMcQuaid** [comment]
@Amorymeltzer Was this fixed by #8710?

**Comment by Amorymeltzer** [comment]
@MikeMcQuaid #8710 took care of it for bash, but AFAICT zsh and fish will still have some issues.
